// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SandwichBucket;

namespace SandwichBucket.Migrations
{
    [DbContext(typeof(SandwichBucketContext))]
    [Migration("20220404193832_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("SandwichBucket.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Description = "O'er the land of the cheese and the home of the brave.",
                            Name = "American Cheese"
                        },
                        new
                        {
                            IngredientId = 2,
                            Description = "I'm better than both Vegemite or Marmite.",
                            Name = "Anchovy Paste"
                        },
                        new
                        {
                            IngredientId = 3,
                            Description = "It's hip 'vocado. And $9 a cut.",
                            Name = "Avocado"
                        },
                        new
                        {
                            IngredientId = 4,
                            Description = "You can't spell 'happiness' without 'bacon'. well, you can. you'd just be miserable spelling it.",
                            Name = "Bacon"
                        },
                        new
                        {
                            IngredientId = 5,
                            Description = "1776 substituted with peppers instead of liberty.",
                            Name = "Bell Peppers"
                        },
                        new
                        {
                            IngredientId = 6,
                            Description = "Ordinary, crumbly cheese if you're colorblind.",
                            Name = "Blue Cheese"
                        },
                        new
                        {
                            IngredientId = 7,
                            Description = "It's nonsense.",
                            Name = "Baloney"
                        },
                        new
                        {
                            IngredientId = 8,
                            Description = "You best believe this is butter.",
                            Name = "Butter"
                        },
                        new
                        {
                            IngredientId = 9,
                            Description = "Human noses. If humans were snow-people.",
                            Name = "Carrot"
                        },
                        new
                        {
                            IngredientId = 10,
                            Description = "A mild-mannered cheese dyed a less intimidating color.",
                            Name = "Cheddar"
                        },
                        new
                        {
                            IngredientId = 11,
                            Description = "A non-confrontational bird.",
                            Name = "Chicken"
                        },
                        new
                        {
                            IngredientId = 12,
                            Description = "Just as much to say as it is to eat.",
                            Name = "Ciabatta Roll"
                        },
                        new
                        {
                            IngredientId = 13,
                            Description = "Cows after a Korn festival, pairs well with cabbage.",
                            Name = "Corned Beef"
                        },
                        new
                        {
                            IngredientId = 14,
                            Description = "Cranberry jelly is so fancy its considered a sauce.",
                            Name = "Cranberry Sauce"
                        },
                        new
                        {
                            IngredientId = 15,
                            Description = "What's that in the sky? It's a cheese? It's a cream? It's a cream cheese!",
                            Name = "Cream Cheese"
                        },
                        new
                        {
                            IngredientId = 16,
                            Description = "Old pickles, if they aged like Benjamin Button.",
                            Name = "Cucumbers"
                        },
                        new
                        {
                            IngredientId = 17,
                            Description = "Please don't put this on your sandwich. It tastes best by itself!",
                            Name = "Daniel Angerer's Human Milk Cheese"
                        },
                        new
                        {
                            IngredientId = 18,
                            Description = "If cucumbers were witches.",
                            Name = "Dill Pickles"
                        },
                        new
                        {
                            IngredientId = 19,
                            Description = "Like wet turkey, only dry.",
                            Name = "Dry Turkey"
                        },
                        new
                        {
                            IngredientId = 20,
                            Description = "There's fried egg, boiled egg, sliced egg, baked egg, salted egg, raw egg, egg burger, salsa'd egg, egg sandwich, egg salad, salad egg, egg fried rice, chicken egg, .... That-that's about it.",
                            Name = "Egg"
                        },
                        new
                        {
                            IngredientId = 21,
                            Description = "Ham. Yup.",
                            Name = "Ham"
                        },
                        new
                        {
                            IngredientId = 22,
                            Description = "A smooth, creamy, supple-in-texture cheese. Can't have a party without havarti.",
                            Name = "Havarti Cheese"
                        },
                        new
                        {
                            IngredientId = 23,
                            Description = "Ya know like that cute costume",
                            Name = "HawtDwag"
                        },
                        new
                        {
                            IngredientId = 24,
                            Description = "During the day, a columnist. At night, a hero roll.",
                            Name = "Hoagie Bun"
                        },
                        new
                        {
                            IngredientId = 25,
                            Description = "How cool is that horse? Eh. That horse is rad-ish.",
                            Name = "Horseradish"
                        },
                        new
                        {
                            IngredientId = 26,
                            Description = "Pairs well with Avocado bread, thick rimmed glasses and The Shins.",
                            Name = "Hummus"
                        },
                        new
                        {
                            IngredientId = 27,
                            Description = "If fruit and sugar got into a car accident and neither were wearing a seatbelt.",
                            Name = "Jam Jellies"
                        },
                        new
                        {
                            IngredientId = 28,
                            Description = "Along with chocolate, makes for an excellent blood substitute with film.",
                            Name = "Ketchup"
                        },
                        new
                        {
                            IngredientId = 29,
                            Description = "A type of karate, filled with vegetables.",
                            Name = "KimChi"
                        },
                        new
                        {
                            IngredientId = 30,
                            Description = "A green blanket, enjoyed by rabbits.",
                            Name = "Lettuce"
                        },
                        new
                        {
                            IngredientId = 31,
                            Description = "Bread, inspired by Vincent van Gogh.",
                            Name = "Marbled Rye Bread"
                        },
                        new
                        {
                            IngredientId = 32,
                            Description = "A trench in the ocean... Not sure what this has to do with sandwiches.",
                            Name = "Marinara"
                        },
                        new
                        {
                            IngredientId = 33,
                            Description = "Im better than Vegemite",
                            Name = "Marmite"
                        },
                        new
                        {
                            IngredientId = 34,
                            Description = "Spread for your bread.",
                            Name = "Mayo"
                        },
                        new
                        {
                            IngredientId = 35,
                            Description = "Boy, sure is nice not havin' Shake around.",
                            Name = "MeatBalls"
                        },
                        new
                        {
                            IngredientId = 36,
                            Description = "Taste like freshly cut grass. Looks like freshly cut grass. is freshly cut grass",
                            Name = "MicroGreens"
                        },
                        new
                        {
                            IngredientId = 37,
                            Description = "A zesty yellow fellow that isn't at all mellow, and can make you bellow.",
                            Name = "Mustard"
                        },
                        new
                        {
                            IngredientId = 38,
                            Description = "Brown spread. Don't worry, it's hazelnut and cocoa.",
                            Name = "Nutella"
                        },
                        new
                        {
                            IngredientId = 39,
                            Description = "I'm a tomato poser.",
                            Name = "Olive Bruschetta"
                        },
                        new
                        {
                            IngredientId = 40,
                            Description = "Be judged by your selection of this at Costco, by Steve, a passerby. Screw you, Steve! I LIKE JIF. I DON'T NEED MY PEANUT-BUTTER TO BE MADE OUT OF ALMONDS. THAT'S YOUR CHOICE. anyway, its peanuts in butter-form.",
                            Name = "Peanut Butter"
                        },
                        new
                        {
                            IngredientId = 41,
                            Description = "Like peppers, but from the east coast.",
                            Name = "PepperCini"
                        },
                        new
                        {
                            IngredientId = 42,
                            Description = "The last name of the family across the street from Bob's business.",
                            Name = "Pesto"
                        },
                        new
                        {
                            IngredientId = 43,
                            Description = "Uncured ham, sliced as thin as Ryan's wallet.",
                            Name = "Prosciutto"
                        },
                        new
                        {
                            IngredientId = 44,
                            Description = "Made in solidary in Provo, Utah.",
                            Name = "Provolone"
                        },
                        new
                        {
                            IngredientId = 45,
                            Description = "'I like my butt rubbed and my pork pulled' - Porky Pig",
                            Name = "Pulled Pork"
                        },
                        new
                        {
                            IngredientId = 46,
                            Description = "These onions were made famous after starring in an action comedy with Bruce Willis.",
                            Name = "Red Onion"
                        },
                        new
                        {
                            IngredientId = 47,
                            Description = "What is relish?",
                            Name = "Relish"
                        },
                        new
                        {
                            IngredientId = 48,
                            Description = "Also known as 'I've got hurt feelings meat' or 'toasted conflict'.",
                            Name = "Roast Beef"
                        },
                        new
                        {
                            IngredientId = 49,
                            Description = "Xena the Warrior Princess's favorite meat, flies well when thrown.",
                            Name = "Salami"
                        },
                        new
                        {
                            IngredientId = 50,
                            Description = "[Insert Europeon Joke Here]",
                            Name = "Sauerkraut"
                        },
                        new
                        {
                            IngredientId = 51,
                            Description = "Allergies be damned!!",
                            Name = "Seitan"
                        },
                        new
                        {
                            IngredientId = 52,
                            Description = "Is this appropriation?",
                            Name = "Slaw"
                        },
                        new
                        {
                            IngredientId = 53,
                            Description = "Sourful and powerful, this bread has a strong opinion on every. Damn. Thing.",
                            Name = "Sourdough Bread"
                        },
                        new
                        {
                            IngredientId = 54,
                            Description = "PastaFarians be craving those noodly apendages.",
                            Name = "Spaghetti"
                        },
                        new
                        {
                            IngredientId = 55,
                            Description = "Soggy lettuce, produces beachball-sized biceps when consumed.",
                            Name = "Spinach"
                        },
                        new
                        {
                            IngredientId = 56,
                            Description = "Created from slightly used yoga mats from the dance studio across the street.",
                            Name = "Subway Yoga Mat Bread"
                        },
                        new
                        {
                            IngredientId = 57,
                            Description = "The best cheese ever, and nobody can poke holes in that fact.",
                            Name = "Swiss Cheese"
                        },
                        new
                        {
                            IngredientId = 58,
                            Description = "Hamburger + Spices = Taco Meat",
                            Name = "Taco Meat"
                        },
                        new
                        {
                            IngredientId = 59,
                            Description = "Low/no sodium, solidified ketchup miniature discuses (frisbees)",
                            Name = "ToeMaToe"
                        },
                        new
                        {
                            IngredientId = 60,
                            Description = "This popular fish is said to be able to take down a lion.",
                            Name = "Tuna"
                        },
                        new
                        {
                            IngredientId = 61,
                            Description = "I'm better than Marmite",
                            Name = "Vegimite"
                        },
                        new
                        {
                            IngredientId = 62,
                            Description = "The most boring of bread, will likely lecture you on politics or something.",
                            Name = "White Bread"
                        },
                        new
                        {
                            IngredientId = 63,
                            Description = "Bread, just disputably healthier for you.",
                            Name = "Whole Wheat Bread"
                        },
                        new
                        {
                            IngredientId = 64,
                            Description = "Cheese from our most music-festival-attending ox.",
                            Name = "Yak Cheese"
                        },
                        new
                        {
                            IngredientId = 65,
                            Description = "No expiration date. Taste test first. Made with love.",
                            Name = "Your Grandma's Breadbox Bread"
                        });
                });

            modelBuilder.Entity("SandwichBucket.Models.IngredientTag", b =>
                {
                    b.Property<int>("IngredientTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("IngredientTagId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("TagId");

                    b.ToTable("IngredientTag");
                });

            modelBuilder.Entity("SandwichBucket.Models.Sandwich", b =>
                {
                    b.Property<int>("SandwichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("SandwichId");

                    b.ToTable("Sandwiches");

                    b.HasData(
                        new
                        {
                            SandwichId = 1,
                            Alignment = 0,
                            Description = "Hell yes",
                            Name = "Banh Mi"
                        },
                        new
                        {
                            SandwichId = 2,
                            Alignment = 0,
                            Description = "Classic",
                            Name = "BLT"
                        },
                        new
                        {
                            SandwichId = 3,
                            Alignment = 0,
                            Description = "Watch out for the burglar",
                            Name = "Cheeseburger"
                        },
                        new
                        {
                            SandwichId = 4,
                            Alignment = 0,
                            Description = "Chop up",
                            Name = "Cheesesteak"
                        },
                        new
                        {
                            SandwichId = 5,
                            Alignment = 0,
                            Description = "Damn fine",
                            Name = "CherryPie"
                        },
                        new
                        {
                            SandwichId = 6,
                            Alignment = 0,
                            Description = "Chicken of the land",
                            Name = "Chicken Salad"
                        },
                        new
                        {
                            SandwichId = 7,
                            Alignment = 0,
                            Description = "Who am I?",
                            Name = "Chopped Liver"
                        },
                        new
                        {
                            SandwichId = 8,
                            Alignment = 0,
                            Description = "Damn fine",
                            Name = "Croque-monsieur"
                        },
                        new
                        {
                            SandwichId = 9,
                            Alignment = 0,
                            Description = "All kinds of pork",
                            Name = "Cubano"
                        },
                        new
                        {
                            SandwichId = 10,
                            Alignment = 0,
                            Description = "Veal or Beef??",
                            Name = "Doner kebab"
                        },
                        new
                        {
                            SandwichId = 11,
                            Alignment = 0,
                            Description = "You're either with it or against it",
                            Name = "Egg Salad"
                        },
                        new
                        {
                            SandwichId = 12,
                            Alignment = 0,
                            Description = "Chickpeas or Garbanzos?",
                            Name = "Falafel"
                        },
                        new
                        {
                            SandwichId = 13,
                            Alignment = 0,
                            Description = "Turkey and slaw baby",
                            Name = "Georgia Reuben"
                        },
                        new
                        {
                            SandwichId = 14,
                            Alignment = 0,
                            Description = "Mayo or Butter???",
                            Name = "Grilled Cheese"
                        },
                        new
                        {
                            SandwichId = 15,
                            Alignment = 0,
                            Description = "GYYY-ROOOE",
                            Name = "Gyro"
                        },
                        new
                        {
                            SandwichId = 16,
                            Alignment = 0,
                            Description = "Some words",
                            Name = "Ham and Swiss"
                        },
                        new
                        {
                            SandwichId = 17,
                            Alignment = 0,
                            Description = "Don't put ketchup on a hot dog",
                            Name = "Hot Dog"
                        },
                        new
                        {
                            SandwichId = 18,
                            Alignment = 0,
                            Description = "You should eat this with a fork",
                            Name = "Meatball Sub"
                        },
                        new
                        {
                            SandwichId = 19,
                            Alignment = 0,
                            Description = "Yum olives",
                            Name = "Muffuletta"
                        },
                        new
                        {
                            SandwichId = 20,
                            Alignment = 0,
                            Description = "Hand eating at its finest",
                            Name = "Pastie"
                        },
                        new
                        {
                            SandwichId = 21,
                            Alignment = 0,
                            Description = "That's it",
                            Name = "PB&J"
                        },
                        new
                        {
                            SandwichId = 22,
                            Alignment = 0,
                            Description = "Fold it",
                            Name = "Pizza"
                        },
                        new
                        {
                            SandwichId = 23,
                            Alignment = 0,
                            Description = "This is making me hungry",
                            Name = "Pulled Pork"
                        },
                        new
                        {
                            SandwichId = 24,
                            Alignment = 0,
                            Description = "Who cares",
                            Name = "Reuben"
                        },
                        new
                        {
                            SandwichId = 25,
                            Alignment = 0,
                            Description = "Gotta be with horsey sauce",
                            Name = "Roast Beef"
                        },
                        new
                        {
                            SandwichId = 26,
                            Alignment = 0,
                            Description = "666",
                            Name = "Seitan"
                        },
                        new
                        {
                            SandwichId = 27,
                            Alignment = 0,
                            Description = "Somehow this is a sandwich",
                            Name = "Spaghetti and Meatballs"
                        },
                        new
                        {
                            SandwichId = 28,
                            Alignment = 0,
                            Description = "A bunch of things",
                            Name = "Sub"
                        },
                        new
                        {
                            SandwichId = 29,
                            Alignment = 0,
                            Description = "Maybe the best of all sandwiches",
                            Name = "Taco"
                        },
                        new
                        {
                            SandwichId = 30,
                            Alignment = 0,
                            Description = "Maybe the best of all sandwiches",
                            Name = "Taco"
                        },
                        new
                        {
                            SandwichId = 31,
                            Alignment = 0,
                            Description = "yum",
                            Name = "Torta"
                        },
                        new
                        {
                            SandwichId = 32,
                            Alignment = 0,
                            Description = "Chicken of the sea",
                            Name = "Tuna Salad"
                        },
                        new
                        {
                            SandwichId = 33,
                            Alignment = 0,
                            Description = "Chicken of the sea",
                            Name = "Tuna Salad"
                        },
                        new
                        {
                            SandwichId = 34,
                            Alignment = 0,
                            Description = "Some dirt between two 2 x 4s",
                            Name = "Wood"
                        });
                });

            modelBuilder.Entity("SandwichBucket.Models.SandwichIngredient", b =>
                {
                    b.Property<int>("SandwichIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("SandwichId")
                        .HasColumnType("int");

                    b.HasKey("SandwichIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("SandwichId");

                    b.ToTable("SandwichesIngredients");
                });

            modelBuilder.Entity("SandwichBucket.Models.SandwichTag", b =>
                {
                    b.Property<int>("SandwichTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SandwichId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SandwichTagId");

                    b.HasIndex("SandwichId");

                    b.HasIndex("TagId");

                    b.ToTable("SandwichesTags");
                });

            modelBuilder.Entity("SandwichBucket.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Basically a dog turd between two pieces of bread"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Building materials"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Closed-faced"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Delicious"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Dog Food"
                        },
                        new
                        {
                            TagId = 6,
                            Name = "Face-Off"
                        },
                        new
                        {
                            TagId = 7,
                            Name = "Fork Necessary"
                        },
                        new
                        {
                            TagId = 8,
                            Name = "Gluten-Free"
                        },
                        new
                        {
                            TagId = 9,
                            Name = "Good mineworker faire"
                        },
                        new
                        {
                            TagId = 10,
                            Name = "Greek"
                        },
                        new
                        {
                            TagId = 11,
                            Name = "Japanese Sando"
                        },
                        new
                        {
                            TagId = 12,
                            Name = "John Travolta's Favorite"
                        },
                        new
                        {
                            TagId = 13,
                            Name = "Lots of Gluten"
                        },
                        new
                        {
                            TagId = 14,
                            Name = "Mexican"
                        },
                        new
                        {
                            TagId = 15,
                            Name = "Nic Cage Approved"
                        },
                        new
                        {
                            TagId = 16,
                            Name = "No-faced"
                        },
                        new
                        {
                            TagId = 17,
                            Name = "Open-faced"
                        },
                        new
                        {
                            TagId = 18,
                            Name = "Pasta"
                        },
                        new
                        {
                            TagId = 19,
                            Name = "People Who Go To Epicodus Would Eat This"
                        },
                        new
                        {
                            TagId = 20,
                            Name = "Savory"
                        },
                        new
                        {
                            TagId = 21,
                            Name = "Smells Like Garbage"
                        },
                        new
                        {
                            TagId = 22,
                            Name = "So Much Gluten You're Going to Develop a Gluten Allergy"
                        },
                        new
                        {
                            TagId = 23,
                            Name = "Sour"
                        },
                        new
                        {
                            TagId = 24,
                            Name = "Straight from Grandma's Kitchen"
                        },
                        new
                        {
                            TagId = 25,
                            Name = "Straight outta Compton"
                        },
                        new
                        {
                            TagId = 26,
                            Name = "Sweet"
                        },
                        new
                        {
                            TagId = 27,
                            Name = "Terrible"
                        },
                        new
                        {
                            TagId = 28,
                            Name = "The Heart Wants Mayo"
                        },
                        new
                        {
                            TagId = 29,
                            Name = "Turkish"
                        },
                        new
                        {
                            TagId = 30,
                            Name = "Two-faced"
                        },
                        new
                        {
                            TagId = 31,
                            Name = "Vegan"
                        },
                        new
                        {
                            TagId = 32,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            TagId = 33,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            TagId = 34,
                            Name = "We Ain't Got Time To Eat (Great for Smoothies)"
                        },
                        new
                        {
                            TagId = 35,
                            Name = "Would Only Feed To My Worst Enemy"
                        },
                        new
                        {
                            TagId = 36,
                            Name = "Wow, I Can't Believe It's Got Gluten"
                        });
                });

            modelBuilder.Entity("SandwichBucket.Models.IngredientTag", b =>
                {
                    b.HasOne("SandwichBucket.Models.Ingredient", "Ingredient")
                        .WithMany("Tags")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandwichBucket.Models.Tag", "Tag")
                        .WithMany("Ingredients")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SandwichBucket.Models.SandwichIngredient", b =>
                {
                    b.HasOne("SandwichBucket.Models.Ingredient", "Ingredient")
                        .WithMany("Sandwiches")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandwichBucket.Models.Sandwich", "Sandwich")
                        .WithMany("Ingredients")
                        .HasForeignKey("SandwichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Sandwich");
                });

            modelBuilder.Entity("SandwichBucket.Models.SandwichTag", b =>
                {
                    b.HasOne("SandwichBucket.Models.Sandwich", "Sandwich")
                        .WithMany("Tags")
                        .HasForeignKey("SandwichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandwichBucket.Models.Tag", "Tag")
                        .WithMany("Sandwiches")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sandwich");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SandwichBucket.Models.Ingredient", b =>
                {
                    b.Navigation("Sandwiches");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SandwichBucket.Models.Sandwich", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SandwichBucket.Models.Tag", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Sandwiches");
                });
#pragma warning restore 612, 618
        }
    }
}
